name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create a Github Release and tag
    uses: blackbird-cloud/github-actions/.github/workflows/release.yml@main
    secrets: inherit