name: Validate and Format

on:
  workflow_dispatch:
  # pull_request_target:
  #   types: [opened, synchronize]

jobs:
  format:
    if: github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    container: blackbirdcloud/terraform-toolkit:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Validate and Format
        env:
          TFENV_TERRAFORM_VERSION: latest-allowed
        run: |
          terraform init -backend=false
          terraform validate
          terraform fmt

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions